import { ref } from 'vue'
import { workflowStore } from '@ayu/common-state'

export const workflowHooks = () => {
  const store = workflowStore()

  /** @description 工作流节点数据，此处为模拟数据 */
  const process = ref({
    id: 'root',
    type: 'start',
    name: '默认发起人',
    formProperties: [],
    child: {
      id: 'end',
      pid: 'root',
      type: 'end',
      name: '结束',
      child: undefined
    }
  })
  store.handleSetProcess(process.value)
  // 属性
  const fields = ref([
    {
      id: '645605899344187820',
      version: null,
      deleted: 0,
      tenantCode: 'test41',
      appId: 'test41',
      metadata: '639148662648972366',
      field: 'aaa',
      label: 'aaa',
      property: 'aaa',
      option: null,
      format: null,
      length: null,
      scale: null,
      required: null,
      validation: null,
      queryVisible: null,
      editVisible: null,
      searchVisible: null,
      searchValue: 'aaa',
      readonly: null,
      editType: 'string',
      javaType: null,
      commentType: null,
      editOption: '{"customs":{"required":false,"minlength":1,"maxlength":100}}',
      refs: null,
      canUpdate: null,
      sort: null,
      columnWidth: null,
      index: 0,
      designated: 'N',
      sourceOrNot: null,
      shipType: null,
      columnGroup: null,
      type: null,
      isPrimary: null,
      defValue: null,
      lcAppId: null,
      update: true
    },
    {
      id: '639148777111528526',
      version: null,
      deleted: 0,
      tenantCode: 'test41',
      appId: 'test41',
      metadata: '639148662648972366',
      field: 'name',
      label: 'name',
      property: 'name',
      option: null,
      format: null,
      length: null,
      scale: null,
      required: true,
      validation: null,
      queryVisible: true,
      editVisible: true,
      searchVisible: true,
      searchValue: 'name',
      readonly: null,
      editType: 'string',
      javaType: null,
      commentType: null,
      editOption: '{"customs":{"required":true}}',
      refs: null,
      canUpdate: null,
      sort: null,
      columnWidth: '100',
      index: 1,
      designated: 'N',
      sourceOrNot: null,
      shipType: null,
      columnGroup: null,
      type: null,
      isPrimary: null,
      defValue: null,
      lcAppId: null,
      update: true
    },
    {
      id: '639148833369728078',
      version: null,
      deleted: 0,
      tenantCode: 'test41',
      appId: 'test41',
      metadata: '639148662648972366',
      field: 'code',
      label: 'code',
      property: 'code',
      option: null,
      format: null,
      length: null,
      scale: null,
      required: true,
      validation: null,
      queryVisible: true,
      editVisible: true,
      searchVisible: true,
      searchValue: 'code',
      readonly: null,
      editType: 'string',
      javaType: null,
      commentType: null,
      editOption: '{"customs":{"required":true}}',
      refs: null,
      canUpdate: null,
      sort: null,
      columnWidth: '100',
      index: 2,
      designated: 'N',
      sourceOrNot: null,
      shipType: null,
      columnGroup: null,
      type: null,
      isPrimary: null,
      defValue: null,
      lcAppId: null,
      update: true
    }
  ])
  return {
    fields
  }
}
