/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
}
